---
- hosts: all
  become: true
  vars:
    vg_name: centos_centos-ks 
    lv_name: root 
    dev: "/dev/sda"
        
  tasks:
      - debug:
          var: dev 

      - name: Get partition information
        parted:
          device: "{{ dev }}"
        register: partinfo
        become: yes

      - debug: var=partinfo

      - set_fact:
          new_partition_required: "{{ (partinfo.partitions[-1].end < partinfo.disk.size) | bool }}"
      
      - debug: var=new_partition_required

      - block:
        - name: "Create a new partition after {{ partinfo.partitions[-1].end }}KiB"
          parted:
            part_start: "{{ partinfo.partitions[-1].end }}KiB"
            device: "{{ dev }}"
            number: "{{ partinfo.partitions[-1].num + 1 }}"
            flags: [ lvm ]
            state: present
          
        - name: Probe kernel about partition table changes
          command: partprobe

        - name: Add the partition to the volume group
          lvg:
            vg: "{{ vg_name }}"
            pvs: "{{ dev }}{{ partinfo.partitions[-1].num }},{{ dev }}{{ partinfo.partitions[-1].num + 1 }}"

        - name: Extend LVM to the whole volume group
          lvol:
            vg: "{{vg_name}}"
            lv: "{{lv_name}}"
            size: +100%FREE
            resizefs: true
        
        when: new_partition_required
    