---
- hosts: localhost
  gather_facts: no        
  tasks:
    - name: get relative path
      set_fact:
        my_rel_path: "{{ '/etc/subdir/some_file.txt' | relpath('/etc') }}"

    - debug:
        var: my_rel_path 

    - name: construct path
      set_fact:
        my_path: "{{ ('some_dir', 'some_file.txt') | path_join }}"

    - debug:
        var: my_path 

    - name: get port with urlsplit
      set_fact:
        my_param: 200

    - set_fact:
        helm2_version_output: "&version.Version{SemVer:\"v2.10.0\", GitCommit:\"9ad53aac42165a5fadc6c87be0dea6b115f93090\", GitTreeState:\"clean\"}"

    - set_fact:
        helm2_client_version: "{{ helm2_version_output | regex_search('(Version|SemVer):\"v(\\d+)\\.(\\d+)\\.(\\d+)\"') | string | regex_search('v(\\d+)\\.(\\d+)\\.(\\d+)') }}"
      
    - debug: var=helm2_client_version
    
    - set_fact:
        helm3_version_output: "version.BuildInfo{Version:\"v3.2.4\", GitCommit:\"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688\", GitTreeState:\"clean\", GoVersion:\"go1.13.12\"}"

    - set_fact:
        helm3_client_version: "{{ helm3_version_output | regex_search('(Version|SemVer):\"v(\\d+)\\.(\\d+)\\.(\\d+)\"') | string | regex_search('v(\\d+)\\.(\\d+)\\.(\\d+)') }}"
    
    - debug: var=helm3_client_version

    - assert:
        that: 
          - helm3_client_version is not defined or helm3_client_version is version('v3.0.0', '>=')
        fail_msg: "helm client present but version is less than 3."
        success_msg: "helm client not yet installed or already at least version 3"

    - set_fact:
        helm3_client_major_version: "{{ helm3_client_version | regex_search('v(\\d+)\\.') | string | regex_search('(\\d+)') }}"

    - debug: var=helm3_client_major_version

    - assert: 
        that:
          - helm3_client_major_version|int == 3
        fail_msg: "helm client is not version 3. Either removed existing helm client or upgrade to helm3"

    - name: get port with urlsplit
      set_fact:
        splitted_port: "{{ 'https://user:password@www.acme.com/dir/index.html?query=term#fragment' | urlsplit('port') }}"

    - debug: var=splitted_port

    - name: get all urlsplit results
      set_fact:
        splitted_url: "{{ 'https://user:password@www.acme.com/dir/index.html?query=term#fragment' | urlsplit }}"

    - debug: var=splitted_url

    - name: set docker_insecure_registries
      set_fact: 
        docker_insecure_registries:
          - '192.168.100.26:5000'

    - name: setting docker_options
      set_fact:
        docker_options: "{{ docker_insecure_registries | map('regex_replace', '^(.*)$', '--insecure-registry=\\1' ) | list | join(' ') }}"
        
    - debug: var=docker_options


